spring:
  application:
    name: eureka-service
eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
     
 
zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8083     
    stock-service:
      path: /stock-service/**
      url: http://localhost:8081